"""empty message

Revision ID: 5ed50d9a8888
Revises: 025dd814df9c
Create Date: 2019-09-07 11:20:58.601088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from msu import models

# revision identifiers, used by Alembic.
revision = '5ed50d9a8888'
down_revision = '025dd814df9c'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    sess = sa.orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'inserted_at',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file', 'updated_at',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('form', 'inserted_at',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post', 'inserted_at',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post', 'updated_at',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    sess = sa.orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'inserted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('form', 'inserted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file', 'inserted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('post', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
