"""empty message

Revision ID: 757c902e2498
Revises: 5ed50d9a8888
Create Date: 2019-12-23 10:47:30.742149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757c902e2498'
down_revision = '5ed50d9a8888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congress_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_congress_member_key'), 'congress_member', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_congress_member_key'), table_name='congress_member')
    op.drop_table('congress_member')
    # ### end Alembic commands ###
