"""empty message

Revision ID: 88028a4dd957
Revises: be4a6b014cb9
Create Date: 2019-08-14 00:22:48.219434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88028a4dd957'
down_revision = 'be4a6b014cb9'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('file', 'filename', new_column_name='key')
    op.alter_column('file', 'name', new_column_name='desc')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('url', sa.Text(), nullable=False))
    op.create_index(op.f('ix_file_key'), 'file', ['key'], unique=True)
    op.drop_column('file', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_file_key'), table_name='file')
    op.drop_column('file', 'url')
    # ### end Alembic commands ###

    op.alter_column('file', 'key', new_column_name='filename')
    op.alter_column('file', 'desc', new_column_name='name')
