"""empty message

Revision ID: cbb2cf951b7e
Revises: 025dd814df9c
Create Date: 2019-12-28 21:25:25.047332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb2cf951b7e'
down_revision = '025dd814df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notif_device',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('os', sa.Text(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_notif_device')
    # ### end Alembic commands ###
