"""empty message

Revision ID: d4779eaf9d22
Revises: 3e862fdf22e8
Create Date: 2020-06-10 15:30:40.937426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4779eaf9d22'
down_revision = '3e862fdf22e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congress_member', sa.Column('file_id', sa.Integer(), nullable=False))
    op.drop_index('ix_congress_member_key', table_name='congress_member')
    op.create_foreign_key(None, 'congress_member', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('congress_member', 'archived')
    op.drop_column('congress_member', 'updated_at')
    op.drop_column('congress_member', 'url')
    op.drop_column('congress_member', 'key')
    op.drop_column('congress_member', 'inserted_at')
    op.add_column('file', sa.Column('hidden', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'hidden')
    op.add_column('congress_member', sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('congress_member', sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('congress_member', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('congress_member', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('congress_member', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'congress_member', type_='foreignkey')
    op.create_index('ix_congress_member_key', 'congress_member', ['key'], unique=True)
    op.drop_column('congress_member', 'file_id')
    # ### end Alembic commands ###
